services:
  fastapi-app:
    build: ./fastapi-app 
    container_name: fastapi-app
    ports:
      - "8000:8000"
    networks:
      - monitoring
    volumes:
      - ./fastapi-collection.json:/app/fastapi-collection.json  # Mount JSON if needed

  prometheus:
    image: prom/prometheus:v2.37.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:9.0.0
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
